/*
Write a program using Go routines. The program takes an input of an integer
a. Routine tries to calculate the sum of odd numbers upto the given number. (3 marks)
b. Routine tries to calculate the sum of even numbers upto the given number.(3 marks)
c. Routine tries to calculate the sum of digits of results generated by a & b. (2 marks)
*/
